/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./NftVault.types";
import * as _1 from "./NftVault.client";
import * as _2 from "./NftVault.message-composer";
import * as _3 from "./NftVault.react-query";
import * as _4 from "./StakeRewards.types";
import * as _5 from "./StakeRewards.client";
import * as _6 from "./StakeRewards.message-composer";
import * as _7 from "./StakeRewards.react-query";
import * as _8 from "./VaultFactory.types";
import * as _9 from "./VaultFactory.client";
import * as _10 from "./VaultFactory.message-composer";
import * as _11 from "./VaultFactory.react-query";
export namespace contracts {
  export const NftVault = {
    ..._0,
    ..._1,
    ..._2,
    ..._3
  };
  export const StakeRewards = {
    ..._4,
    ..._5,
    ..._6,
    ..._7
  };
  export const VaultFactory = {
    ..._8,
    ..._9,
    ..._10,
    ..._11
  };
}