/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  rewards_code_id: number;
  vault_code_id: number;
}
export type ExecuteMsg = ExecMsg;
export type ExecMsg = {
  update_config: {
    rewards_code_id?: number | null;
    vault_code_id?: number | null;
  };
} | {
  create_vault: {
    collections: string[];
    unstaking_duration_sec: number;
    vault_label: string;
  };
};
export type QueryMsg = QueryMsg1;
export type QueryMsg1 = {
  vaults: {
    query_options: QueryOptionsForUint64;
  };
};
export type QueryBoundForUint64 = {
  inclusive: number;
} | {
  exclusive: number;
};
export interface QueryOptionsForUint64 {
  descending?: boolean | null;
  limit?: number | null;
  max?: QueryBoundForUint64 | null;
  min?: QueryBoundForUint64 | null;
}
export type Addr = string;
export type ArrayOfTupleOfUint64AndAddr = [number, Addr][];